<?php 

// Class DataGrab - Created On: 2019-10-29 at 02:10:52

 if(!class_exists('DataGrabber')){
  class DataGrabber{
      var $today;
      private $m_fields;
      private $m_values;
      private $m_sql;
      public $Fields;
      public $Values;
      public $Sql;
      private $is_local;

      function __construct( $is_local ){
          $this->today = date( 'Y-m-d' );
          $this::Initialize();
          $this->is_local = $is_local;
      } 

      private function Initialize(){
            $this->Fields='';
            $this->Values='';
            $this->Sql='';
      }

      public function GetSuggestedUrls(){
            $dbOps = new clsDBOps();
            $ret = new clsRetval();
            $mySql = "SELECT created_date, url FROM `url_suggestions` WHERE approved=1";
            $ret = $dbOps->ExecuteSelectQuery(new ConnectionProperties( $is_local ), $mySql );

      }

      public function GetPolsResults($polls_html){
            $polls_lc = strtolower($polls_html);
            $iPre0 = stripos($polls_lc,'qchart');
            $iPre1 = stripos($polls_lc,'<pre>',$iPre0);
            $iPre2 = stripos($polls_lc,'</pre>',$iPre1);
            return ($iPre0 >0) ? substr($polls_html,$iPre1,($iPre2-$iPre1)) : '';
      }

      public function AnalyzeServer(){
            $dbOps = new clsDBOps();
            $ret = new clsRetval();
            $sql = "SELECT SERVER FROM `data_collection` WHERE SERVER IS NOT NULL AND SERVER != '' ORDER BY ID DESC";
            $json = '';

            $ret = $dbOps->ExecuteSelectQuery(new ConnectionProperties( $is_local ), $sql);

            if($ret->retval['status']=='OK'){
                  foreach($ret->retval['record_set'] as $k=>$v){
                        $json = json_decode($v);
                  }
            }
      }

      /**
        * Get a web file (HTML, XHTML, XML, image, etc.) from a URL.  Return an
        * array containing the HTTP server response header fields and content.
        */
       function get_web_page( $url )
       {
           $user_agent='Mozilla/5.0 (Windows NT 6.1; rv:8.0) Gecko/20100101 Firefox/8.0';
   
           $options = array(
   
               CURLOPT_CUSTOMREQUEST  =>"GET",        //set request type post or get
               CURLOPT_POST           =>false,        //set to GET
               CURLOPT_USERAGENT      => $user_agent, //set user agent
               CURLOPT_COOKIEFILE     =>"cookie.txt", //set cookie file
               CURLOPT_COOKIEJAR      =>"cookie.txt", //set cookie jar
               CURLOPT_RETURNTRANSFER => true,     // return web page
               CURLOPT_HEADER         => false,    // don't return headers
               CURLOPT_FOLLOWLOCATION => true,     // follow redirects
               CURLOPT_ENCODING       => "",       // handle all encodings
               CURLOPT_AUTOREFERER    => true,     // set referer on redirect
               CURLOPT_CONNECTTIMEOUT => 120,      // timeout on connect
               CURLOPT_TIMEOUT        => 120,      // timeout on response
               CURLOPT_MAXREDIRS      => 10,       // stop after 10 redirects
           );
   
           $ch      = curl_init( $url );
           curl_setopt_array( $ch, $options );
           $content = curl_exec( $ch );
           $err     = curl_errno( $ch );
           $errmsg  = curl_error( $ch );
           $header  = curl_getinfo( $ch );
           curl_close( $ch );
   
           $header['errno']   = $err;
           $header['errmsg']  = $errmsg;
           $header['content'] = $content;
           return $header;
       }
                  
	public function SaveUrl( $url, $hash, $remote_addr, $title, $itsme=false ){
            $sql="";
            $newTitle = "";
            $filthCheckOne = "";
            $filthCheckTwo = "";
            $dbOps = new clsDBOps();
            $ret = new clsRetval();
            $tools = new clsTools();
            $url = $tools->clean_sql( $url );
            $title = $tools->clean_sql( $title );
            $title = strtolower( $title );
            $title = ucwords( $title );
            $newUrl='';
            $approved='0';

            // First check url for swears
            $urlSpaced =preg_replace( '/[^a-z\d ]/i', ' ', $url );
            $aryUrl = explode(' ', $urlSpaced);
            $foundFilth = false;

            foreach($aryUrl as $k=>$v){
                  $foundFilth = trim($this::FindFilth($v));
                  if($foundFilth){
                        break;
                  }
            }

            if($foundFilth){
                  $ret->retval['status'] = 'notOK';
                  $ret->retval['url_swears'] = 'true';
                  $ret->retval['msg'] = 'NO SWEAR WORDS PLEASE!!!';
            }else{

                  // Next check title for swears .. either fail on swears or insert our data into table
                  $aryTitle = explode(' ', $title);
                  foreach($aryTitle as $k=>$v){
                        $filthCheckOne = trim($this::FilterFilth($v));
                        $filthCheckTwo .= trim($this::FilterFilth($v));
                        if(strlen($filthCheckOne)>0){
                              $newTitle .= $filthCheckOne.' ';
                        }
                  }
      
                  if($filthCheckTwo == ''){
                        $ret->retval['status'] = 'notOK';
                        $ret->retval['title_swears'] = 'true';
                        $ret->retval['msg'] = 'NO SWEAR WORDS PLEASE!!!';
                  }else{
                        $newTitle = trim($newTitle);
                        $newTitle = strtolower($newTitle);
                        $newTitle = ucwords($newTitle);
                        $approved = ( $itsme === true ) ? '1' : '0';
                        $sql = "INSERT INTO `url_suggestions`(`approved`, `created_date`, `REMOTE_ADDR`, `hash`, `url`,`title`) VALUES('".$approved."', '".date('Y-m-d H:m:s')."','".$remote_addr."','".$hash."','".$url."','".$newTitle."');";
                        $ret = $dbOps->ExecuteInsertQuery(new ConnectionProperties( $this->is_local ), $sql );
                  }
            }

            unset ( $dbOps, $tools );

            echo json_encode($ret);
      }

      public function FindFilth($word){
            $FilthyWords = $this::get_swear_words();
            return ( in_array( strtolower( $word ), $FilthyWords ) ) ? true : false;
            unset( $FilthyWords );

      } // End FilterFilth()

      public function FilterFilth($word){
            $FilthyWords = $this::get_swear_words();
            return ( in_array( strtolower( $word ), $FilthyWords ) ) ? '' : $word;
            unset( $FilthyWords );

      } // End FilterFilth()

      public function GrabGlobalsSql(){

            if(isset($_SERVER['REMOTE_ADDR'])){
                  if($_SERVER['REMOTE_ADDR']=='24.250.48.133'){
                        return false;
                  }
            }

        $this::set_Sql("INSERT INTO `data_collection`(`created_date`,");

        if(isset($_SERVER) && ( json_encode($_SERVER, JSON_HEX_QUOT) != '[]')){
            $this::set_Fields("`SERVER`,");
            $this::set_Values("'".json_encode($_SERVER, JSON_HEX_QUOT)."',");
        }

        if(isset($_REQUEST) && json_encode($_REQUEST, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`REQUEST`,");
			$this::set_Values("'".json_encode($_REQUEST, JSON_HEX_QUOT)."',");
		}

        if(isset($_POST) && json_encode($_POST, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`POST`,");
			$this::set_Values("'".json_encode($_POST, JSON_HEX_QUOT)."',");
		}

		if(isset($_GET) && json_encode($_GET, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`GET`,");
			$this::set_Values("'".json_encode($_GET, JSON_HEX_QUOT)."',");
		}

		if(isset($_FILES) && json_encode($_FILES, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`FILES`,");
			$this::set_Values("'".json_encode($_FILES, JSON_HEX_QUOT)."',");
		}

		if(isset($_ENV) && json_encode($_ENV, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`ENV`,");
			$this::set_Values("'".json_encode($_ENV, JSON_HEX_QUOT)."',");
		}

		if(isset($_COOKIE) && json_encode($_COOKIE, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`COOKIE`,");
			$this::set_Values("'".json_encode($_COOKIE, JSON_HEX_QUOT)."',");
		}

		if(isset($_SESSION) && json_encode($_SESSION, JSON_HEX_QUOT) != '[]' ){
			$this::set_Fields("`SESSION`,");
			$this::set_Values("'".json_encode($_SESSION, JSON_HEX_QUOT)."',");
		}

        $this::set_Sql(substr($this::get_Fields(),0,strlen($this::get_Fields())-2) . "`) VALUES('".date('Y-m-d H:m:s')."'," . substr($this::get_Values(),0,strlen($this::get_Values())-2)."');");

        return $this::get_Sql();
	  }
	  
      // Fields
      public function set_Fields( $m_fields ){
            $this->Fields .= $m_fields;
      }
      public function get_Fields(){
            return $this->Fields;
      }
      
      // Values
      public function set_Values( $m_values ){
            $this->Values .= $m_values;
      }
      public function get_Values(){
            return $this->Values;
      }
      
      // Sql
      public function set_Sql( $m_sql ){
            $this->Sql .= $m_sql;
      }
      public function get_Sql(){
            return $this->Sql;
      }
  

      private function get_swear_words(){
           return array(
                  '0' => '4r5e',
                  '1' => '50 yard cunt punt',
                  '2' => '5h1t',
                  '3' => '5hit',
                  '4' => 'a_s_s',
                  '5' => 'a2m',
                  '6' => 'a$$',
                  '7' => 'a55',
                  '8' => 'a$$hole',
                  '9' => 'a55hole',
                  '10' => 'adult',
                  '11' => 'aeolus',
                  '12' => 'ahole',
                  '13' => 'amateur',
                  '14' => 'anal',
                  '15' => 'anal impaler',
                  '16' => 'anal leakage',
                  '17' => 'analprobe',
                  '18' => 'anilingus',
                  '19' => 'anus',
                  '20' => 'ar5e',
                  '21' => 'areola',
                  '22' => 'areole',
                  '23' => 'arian',
                  '24' => 'arrse',
                  '25' => 'arse',
                  '26' => 'arsehole',
                  '27' => 'aryan',
                  '28' => 'ass',
                  '29' => 'ass fuck',
                  '30' => 'ass hole',
                  '31' => 'ass-fucker',
                  '32' => 'assbang',
                  '33' => 'assbanged',
                  '34' => 'assbangs',
                  '35' => 'asses',
                  '36' => 'assfuck',
                  '37' => 'assfucker',
                  '38' => 'assfukka',
                  '39' => 'assh0le',
                  '40' => 'asshat',
                  '41' => 'assho1e',
                  '42' => 'asshole',
                  '43' => 'assholes',
                  '44' => 'assmaster',
                  '45' => 'assmucus',
                  '46' => 'assmunch',
                  '47' => 'asswhole',
                  '48' => 'asswipe',
                  '49' => 'asswipes',
                  '50' => 'autoerotic',
                  '51' => 'azazel',
                  '52' => 'azz',
                  '53' => 'b!tch',
                  '54' => 'b00bs',
                  '55' => 'b17ch',
                  '56' => 'b1tch',
                  '57' => 'babe',
                  '58' => 'babes',
                  '59' => 'ballbag',
                  '60' => 'ballsack',
                  '61' => 'bang',
                  "62" => "bang (one's) box",
                  '63' => 'bangbros',
                  '64' => 'banger',
                  '65' => 'bareback',
                  '66' => 'barf',
                  '67' => 'bastard',
                  '68' => 'bastards',
                  '69' => 'bawdy',
                  '70' => 'beaner',
                  '71' => 'beardedclam',
                  '72' => 'beastial',
                  '73' => 'beastiality',
                  '74' => 'beatch',
                  '75' => 'beater',
                  '76' => 'beaver',
                  '77' => 'beef curtain',
                  '78' => 'beer',
                  '79' => 'beeyotch',
                  '80' => 'bellend',
                  '81' => 'beotch',
                  '82' => 'bestial',
                  '83' => 'bestiality',
                  '84' => 'bi+ch',
                  '85' => 'biatch',
                  '86' => 'big tits',
                  '87' => 'bigtits',
                  '88' => 'bimbo',
                  '89' => 'bimbos',
                  '90' => 'birdlock',
                  '91' => 'bitch',
                  '92' => 'bitch tit',
                  '93' => 'bitched',
                  '94' => 'bitcher',
                  '95' => 'bitchers',
                  '96' => 'bitches',
                  '97' => 'bitchin',
                  '98' => 'bitching',
                  '99' => 'bitchy',
                  '100' => 'bloody',
                  '101' => 'blow',
                  '102' => 'blow job',
                  '103' => 'blow me',
                  '104' => 'blow mud',
                  '105' => 'blowjob',
                  '106' => 'blowjobs',
                  '107' => 'blue waffle',
                  '108' => 'blumpkin',
                  '109' => 'bod',
                  '110' => 'bodily',
                  '111' => 'boink',
                  '112' => 'boiolas',
                  '113' => 'bollock',
                  '114' => 'bollocks',
                  '115' => 'bollok',
                  '116' => 'bone',
                  '117' => 'boned',
                  '118' => 'boner',
                  '119' => 'boners',
                  '120' => 'bong',
                  '121' => 'boob',
                  '122' => 'boobies',
                  '123' => 'boobs',
                  '124' => 'booby',
                  '125' => 'booger',
                  '126' => 'bookie',
                  '127' => 'booobs',
                  '128' => 'boooobs',
                  '129' => 'booooobs',
                  '130' => 'booooooobs',
                  '131' => 'bootee',
                  '132' => 'bootie',
                  '133' => 'booty',
                  '134' => 'booze',
                  '135' => 'boozer',
                  '136' => 'boozy',
                  '137' => 'bosom',
                  '138' => 'bosomy',
                  '139' => 'bowel',
                  '140' => 'bowels',
                  '141' => 'bra',
                  '142' => 'brassiere',
                  '143' => 'breast',
                  '144' => 'breasts',
                  '145' => 'buceta',
                  '146' => 'bugger',
                  '147' => 'bukkake',
                  '148' => 'bull shit',
                  '149' => 'bullshit',
                  '150' => 'bullshits',
                  '151' => 'bullshitted',
                  '152' => 'bullturds',
                  '153' => 'bum',
                  '154' => 'bung',
                  '155' => 'bunny fucker',
                  '156' => 'bust a load',
                  '157' => 'busty',
                  '158' => 'butt',
                  '159' => 'butt fuck',
                  '160' => 'butt fuck',
                  '161' => 'buttfuck',
                  '162' => 'buttfucker',
                  '163' => 'butthole',
                  '164' => 'buttmuch',
                  '165' => 'buttplug',
                  '166' => 'c-0-c-k',
                  '167' => 'c-o-c-k',
                  '168' => 'c-u-n-t',
                  '169' => 'c.0.c.k',
                  '170' => 'c.o.c.k.',
                  '171' => 'c.u.n.t',
                  '172' => 'c0ck',
                  '173' => 'c0cksucker',
                  '174' => 'caca',
                  '175' => 'cahone',
                  '176' => 'cameltoe',
                  '177' => 'carpet muncher',
                  '178' => 'carpetmuncher',
                  '179' => 'cawk',
                  '180' => 'cervix',
                  '181' => 'chinc',
                  '182' => 'chincs',
                  '183' => 'chink',
                  '184' => 'choade',
                  '185' => 'chode',
                  '186' => 'chodes',
                  '187' => 'chota bags',
                  '188' => 'cipa',
                  '189' => 'cl1t',
                  '190' => 'climax',
                  '191' => 'clit',
                  '192' => 'clit licker',
                  '193' => 'clitoris',
                  '194' => 'clitorus',
                  '195' => 'clits',
                  '196' => 'clitty',
                  '197' => 'clitty litter',
                  '198' => 'clusterfuck',
                  '199' => 'cnut',
                  '200' => 'cocain',
                  '201' => 'cocaine',
                  '202' => 'cock',
                  '203' => 'cock pocket',
                  '204' => 'cock snot',
                  '205' => 'cock sucker',
                  '206' => 'cock-sucker',
                  '207' => 'cockblock',
                  '208' => 'cockface',
                  '209' => 'cockhead',
                  '210' => 'cockholster',
                  '211' => 'cockknocker',
                  '212' => 'cockmunch',
                  '213' => 'cockmuncher',
                  '214' => 'cocks',
                  '215' => 'cocksmoker',
                  '216' => 'cocksuck',
                  '217' => 'cocksucked',
                  '218' => 'cocksucker',
                  '219' => 'cocksucking',
                  '220' => 'cocksucks',
                  '221' => 'cocksuka',
                  '222' => 'cocksukka',
                  '223' => 'coital',
                  '224' => 'cok',
                  '225' => 'cokmuncher',
                  '226' => 'coksucka',
                  '227' => 'commie',
                  '228' => 'condom',
                  '229' => 'coon',
                  '230' => 'coons',
                  '231' => 'cop some wood',
                  '232' => 'corksucker',
                  '233' => 'cornhole',
                  '234' => 'corp whore',
                  '235' => 'cox',
                  '236' => 'crabs',
                  '237' => 'crack',
                  '238' => 'cracker',
                  '239' => 'crackwhore',
                  '240' => 'crap',
                  '241' => 'crappy',
                  '242' => 'cum',
                  '243' => 'cum chugger',
                  '244' => 'cum dumpster',
                  '245' => 'cum freak',
                  '246' => 'cum guzzler',
                  '247' => 'cumdump',
                  '248' => 'cummer',
                  '249' => 'cummin',
                  '250' => 'cumming',
                  '251' => 'cums',
                  '252' => 'cumshot',
                  '253' => 'cumshots',
                  '254' => 'cumslut',
                  '255' => 'cumstain',
                  '256' => 'cunilingus',
                  '257' => 'cunillingus',
                  '258' => 'cunnilingus',
                  '259' => 'cunny',
                  '260' => 'cunt',
                  '261' => 'cunt hair',
                  '262' => 'cunt-struck',
                  '263' => 'cuntbag',
                  '264' => 'cuntface',
                  '265' => 'cunthunter',
                  '266' => 'cuntlick',
                  '267' => 'cuntlick',
                  '268' => 'cuntlicker',
                  '269' => 'cuntlicker',
                  '270' => 'cuntlicking',
                  '271' => 'cunts',
                  '272' => 'cuntsicle',
                  '273' => 'cut rope',
                  '274' => 'cyalis',
                  '275' => 'cyberfuc',
                  '276' => 'cyberfuck',
                  '277' => 'cyberfucked',
                  '278' => 'cyberfucker',
                  '279' => 'cyberfuckers',
                  '280' => 'cyberfucking',
                  '281' => 'd0ng',
                  '282' => 'd0uch3',
                  '283' => 'd0uche',
                  '284' => 'd1ck',
                  '285' => 'd1ld0',
                  '286' => 'd1ldo',
                  '287' => 'dago',
                  '288' => 'dagos',
                  '289' => 'dammit',
                  '290' => 'damn',
                  '291' => 'damned',
                  '292' => 'damnit',
                  '293' => 'dawgie-style',
                  '294' => 'dick',
                  '295' => 'dick hole',
                  '296' => 'dick shy',
                  '297' => 'dick-ish',
                  '298' => 'dickbag',
                  '299' => 'dickdipper',
                  '300' => 'dickface',
                  '301' => 'dickflipper',
                  '302' => 'dickhead',
                  '303' => 'dickheads',
                  '304' => 'dickish',
                  '305' => 'dickripper',
                  '306' => 'dicksipper',
                  '307' => 'dickweed',
                  '308' => 'dickwhipper',
                  '309' => 'dickzipper',
                  '310' => 'diddle',
                  '311' => 'dike',
                  '312' => 'dildo',
                  '313' => 'dildos',
                  '314' => 'diligaf',
                  '315' => 'dillweed',
                  '316' => 'dimwit',
                  '317' => 'dingle',
                  '318' => 'dink',
                  '319' => 'dinks',
                  '320' => 'dipship',
                  '321' => 'dirsa',
                  '322' => 'dirty Sanchez',
                  '323' => 'dlck',
                  '324' => 'dog-fucker',
                  '325' => 'doggie style',
                  '326' => 'doggie-style',
                  '327' => 'doggiestyle',
                  '328' => 'doggin',
                  '329' => 'dogging',
                  '330' => 'doggy-style',
                  '331' => 'dong',
                  '332' => 'donkeyribber',
                  '333' => 'doofus',
                  '334' => 'doosh',
                  '335' => 'dopey',
                  '336' => 'douch3',
                  '337' => 'douche',
                  '338' => 'douchebag',
                  '339' => 'douchebags',
                  '340' => 'douchey',
                  '341' => 'drunk',
                  '342' => 'duche',
                  '343' => 'dumass',
                  '344' => 'dumbass',
                  '345' => 'dumbasses',
                  '346' => 'dummy',
                  '347' => 'dyke',
                  '348' => 'dykes',
                  '349' => 'eat a dick',
                  '350' => 'eat hair pie',
                  '351' => 'ejaculate',
                  '352' => 'ejaculated',
                  '353' => 'ejaculates',
                  '354' => 'ejaculating',
                  '355' => 'ejaculatings',
                  '356' => 'ejaculation',
                  '357' => 'ejakulate',
                  '358' => 'enlargement',
                  '359' => 'erect',
                  '360' => 'erection',
                  '361' => 'erotic',
                  '362' => 'essohbee',
                  '363' => 'extacy',
                  '364' => 'extasy',
                  '365' => 'f u c k',
                  '366' => 'f u c k e r',
                  '367' => 'f_u_c_k',
                  '368' => 'f-u-c-k',
                  '369' => 'f.u.c.k',
                  '370' => 'f4nny',
                  '371' => 'facial',
                  '372' => 'fack',
                  '373' => 'fag',
                  '374' => 'fagg',
                  '375' => 'fagged',
                  '376' => 'fagging',
                  '377' => 'faggit',
                  '378' => 'faggitt',
                  '379' => 'faggot',
                  '380' => 'faggs',
                  '381' => 'fagot',
                  '382' => 'fagots',
                  '383' => 'fags',
                  '384' => 'faig',
                  '385' => 'faigt',
                  '386' => 'fanny',
                  '387' => 'fannybandit',
                  '388' => 'fannyflaps',
                  '389' => 'fannyfucker',
                  '390' => 'fanyy',
                  '391' => 'fart',
                  '392' => 'fartknocker',
                  '393' => 'fat',
                  '394' => 'fatass',
                  '395' => 'fcuk',
                  '396' => 'fcuker',
                  '397' => 'fcuking',
                  '398' => 'feck',
                  '399' => 'fecker',
                  '400' => 'felch',
                  '401' => 'felcher',
                  '402' => 'felching',
                  '403' => 'fellate',
                  '404' => 'fellatio',
                  '405' => 'feltch',
                  '406' => 'feltcher',
                  '407' => 'fingerfuck',
                  '408' => 'fingerfucked',
                  '409' => 'fingerfucker',
                  '410' => 'fingerfuckers',
                  '411' => 'fingerfucking',
                  '412' => 'fingerfucks',
                  '413' => 'fist fuck',
                  '414' => 'fisted',
                  '415' => 'fistfuck',
                  '416' => 'fistfucked',
                  '417' => 'fistfucker',
                  '418' => 'fistfuckers',
                  '419' => 'fistfucking',
                  '420' => 'fistfuckings',
                  '421' => 'fistfucks',
                  '422' => 'fisting',
                  '423' => 'fisty',
                  '424' => 'flange',
                  '425' => 'flog the log',
                  '426' => 'floozy',
                  '427' => 'foad',
                  '428' => 'fondle',
                  '429' => 'foobar',
                  '430' => 'fook',
                  '431' => 'fooker',
                  '432' => 'foreskin',
                  '433' => 'freex',
                  '434' => 'frigg',
                  '435' => 'frigga',
                  '436' => 'fubar',
                  '437' => 'fuck',
                  '438' => 'fuck',
                  '439' => 'fuck hole',
                  '440' => 'fuck puppet',
                  '441' => 'fuck trophy',
                  '442' => 'fuck yo mama',
                  '443' => 'fuck-ass',
                  '444' => 'fuck-bitch',
                  '445' => 'fuck-tard',
                  '446' => 'fucka',
                  '447' => 'fuckass',
                  '448' => 'fucked',
                  '449' => 'fucker',
                  '450' => 'fuckers',
                  '451' => 'fuckface',
                  '452' => 'fuckhead',
                  '453' => 'fuckheads',
                  '454' => 'fuckin',
                  '455' => 'fucking',
                  '456' => 'fuckings',
                  '457' => 'fuckingshitmotherfucker',
                  '458' => 'fuckme',
                  '459' => 'fuckmeat',
                  '460' => 'fucknugget',
                  '461' => 'fucknut',
                  '462' => 'fuckoff',
                  '463' => 'fucks',
                  '464' => 'fucktard',
                  '465' => 'fucktoy',
                  '466' => 'fuckup',
                  '467' => 'fuckwad',
                  '468' => 'fuckwhit',
                  '469' => 'fuckwit',
                  '470' => 'fudge packer',
                  '471' => 'fudgepacker',
                  '472' => 'fuk',
                  '473' => 'fuker',
                  '474' => 'fukker',
                  '475' => 'fukkin',
                  '476' => 'fuks',
                  '477' => 'fukwhit',
                  '478' => 'fukwit',
                  '479' => 'fux',
                  '480' => 'fux0r',
                  '481' => 'fvck',
                  '482' => 'fxck',
                  '483' => 'g-spot',
                  '484' => 'gae',
                  '485' => 'gai',
                  '486' => 'gang-bang',
                  '487' => 'gangbang',
                  '488' => 'gangbang',
                  '489' => 'gangbanged',
                  '490' => 'gangbangs',
                  '491' => 'ganja',
                  '492' => 'gassy ass',
                  '493' => 'gay',
                  '494' => 'gaylord',
                  '495' => 'gays',
                  '496' => 'gaysex',
                  '497' => 'gey',
                  '498' => 'gfy',
                  '499' => 'ghay',
                  '500' => 'ghey',
                  '501' => 'gigolo',
                  '502' => 'glans',
                  '503' => 'goatse',
                  '504' => 'god',
                  '505' => 'god damn',
                  '506' => 'god-dam',
                  '507' => 'god-damned',
                  '508' => 'godamn',
                  '509' => 'godamnit',
                  '510' => 'goddam',
                  '511' => 'goddammit',
                  '512' => 'goddamn',
                  '513' => 'goddamned',
                  '514' => 'goldenshower',
                  '515' => 'gonad',
                  '516' => 'gonads',
                  '517' => 'gook',
                  '518' => 'gooks',
                  '519' => 'gringo',
                  '520' => 'gspot',
                  '521' => 'gtfo',
                  '522' => 'guido',
                  '523' => 'h0m0',
                  '524' => 'h0mo',
                  '525' => 'ham flap',
                  '526' => 'handjob',
                  '527' => 'hard on',
                  '528' => 'hardcoresex',
                  '529' => 'he11',
                  '530' => 'hebe',
                  '531' => 'heeb',
                  '532' => 'hell',
                  '533' => 'hemp',
                  '534' => 'heroin',
                  '535' => 'herp',
                  '536' => 'herpes',
                  '537' => 'herpy',
                  '538' => 'heshe',
                  '539' => 'hitler',
                  '540' => 'hiv',
                  '541' => 'hoar',
                  '542' => 'hoare',
                  '543' => 'hobag',
                  '544' => 'hoer',
                  '545' => 'hom0',
                  '546' => 'homey',
                  '547' => 'homo',
                  '548' => 'homoerotic',
                  '549' => 'homoey',
                  '550' => 'honky',
                  '551' => 'hooch',
                  '552' => 'hookah',
                  '553' => 'hooker',
                  '554' => 'hoor',
                  '555' => 'hootch',
                  '556' => 'hooter',
                  '557' => 'hooters',
                  '558' => 'hore',
                  '559' => 'horniest',
                  '560' => 'horny',
                  '561' => 'hotsex',
                  '562' => 'how to kill',
                  '563' => 'how to murdep',
                  '564' => 'hump',
                  '565' => 'humped',
                  '566' => 'humping',
                  '567' => 'hussy',
                  '568' => 'hymen',
                  '569' => 'inbred',
                  '570' => 'incest',
                  '571' => 'injun',
                  '572' => 'j3rk0ff',
                  '573' => 'jack-off',
                  '574' => 'jackass',
                  '575' => 'jackhole',
                  '576' => 'jackoff',
                  '577' => 'jap',
                  '578' => 'japs',
                  '579' => 'jerk',
                  '580' => 'jerk-off',
                  '581' => 'jerk0ff',
                  '582' => 'jerked',
                  '583' => 'jerkoff',
                  '584' => 'jism',
                  '585' => 'jiz',
                  '586' => 'jizm',
                  '587' => 'jizz',
                  '588' => 'jizzed',
                  '589' => 'junkie',
                  '590' => 'junky',
                  '591' => 'kawk',
                  '592' => 'kike',
                  '593' => 'kikes',
                  '594' => 'kill',
                  '595' => 'kinky',
                  '596' => 'kinky Jesus',
                  '597' => 'kkk',
                  '598' => 'klan',
                  '599' => 'knob',
                  '600' => 'knob end',
                  '601' => 'knobead',
                  '602' => 'knobed',
                  '603' => 'knobend',
                  '604' => 'knobhead',
                  '605' => 'knobjocky',
                  '606' => 'knobjokey',
                  '607' => 'kock',
                  '608' => 'kondum',
                  '609' => 'kondums',
                  '610' => 'kooch',
                  '611' => 'kooches',
                  '612' => 'kootch',
                  '613' => 'kraut',
                  '614' => 'kum',
                  '615' => 'kummer',
                  '616' => 'kumming',
                  '617' => 'kums',
                  '618' => 'kunilingus',
                  '619' => 'kwif',
                  '620' => 'kyke',
                  '621' => 'l3i+ch',
                  '622' => 'l3itch',
                  '623' => 'labia',
                  '624' => 'lech',
                  '625' => 'LEN',
                  '626' => 'leper',
                  '627' => 'lesbians',
                  '628' => 'lesbo',
                  '629' => 'lesbos',
                  '630' => 'lez',
                  '631' => 'lezbian',
                  '632' => 'lezbians',
                  '633' => 'lezbo',
                  '634' => 'lezbos',
                  '635' => 'lezzie',
                  '636' => 'lezzies',
                  '637' => 'lezzy',
                  '638' => 'lmao',
                  '639' => 'lmfao',
                  '640' => 'loin',
                  '641' => 'loins',
                  '642' => 'lube',
                  '643' => 'lust',
                  '644' => 'lusting',
                  '645' => 'lusty',
                  '646' => 'm-fucking',
                  '647' => 'm0f0',
                  '648' => 'm0fo',
                  '649' => 'm45terbate',
                  '650' => 'ma5terb8',
                  '651' => 'ma5terbate',
                  '652' => 'mafugly',
                  '653' => 'mams',
                  '654' => 'masochist',
                  '655' => 'massa',
                  '656' => 'master-bate',
                  '657' => 'masterb8',
                  '658' => 'masterbat*',
                  '659' => 'masterbat3',
                  '660' => 'masterbate',
                  '661' => 'masterbating',
                  '662' => 'masterbation',
                  '663' => 'masterbations',
                  '664' => 'masturbate',
                  '665' => 'masturbating',
                  '666' => 'masturbation',
                  '667' => 'maxi',
                  '668' => 'menses',
                  '669' => 'menstruate',
                  '670' => 'menstruation',
                  '671' => 'meth',
                  '672' => 'mo-fo',
                  '673' => 'mof0',
                  '674' => 'mofo',
                  '675' => 'molest',
                  '676' => 'moolie',
                  '677' => 'moron',
                  '678' => 'mothafuck',
                  '679' => 'mothafucka',
                  '680' => 'mothafuckas',
                  '681' => 'mothafuckaz',
                  '682' => 'mothafucked',
                  '683' => 'mothafucker',
                  '684' => 'mothafuckers',
                  '685' => 'mothafuckin',
                  '686' => 'mothafucking',
                  '687' => 'mothafuckings',
                  '688' => 'mothafucks',
                  '689' => 'mother fucker',
                  '690' => 'mother fucker',
                  '691' => 'motherfuck',
                  '692' => 'motherfucka',
                  '693' => 'motherfucked',
                  '694' => 'motherfucker',
                  '695' => 'motherfuckers',
                  '696' => 'motherfuckin',
                  '697' => 'motherfucking',
                  '698' => 'motherfuckings',
                  '699' => 'motherfuckka',
                  '700' => 'motherfucks',
                  '701' => 'mtherfucker',
                  '702' => 'mthrfucker',
                  '703' => 'mthrfucking',
                  '704' => 'muff',
                  '705' => 'muff puff',
                  '706' => 'muffdiver',
                  '707' => 'murder',
                  '708' => 'mutha',
                  '709' => 'muthafecker',
                  '710' => 'muthafuckaz',
                  '711' => 'muthafucker',
                  '712' => 'muthafuckker',
                  '713' => 'muther',
                  '714' => 'mutherfucker',
                  '715' => 'mutherfucking',
                  '716' => 'muthrfucking',
                  '717' => 'n1gga',
                  '718' => 'n1gger',
                  '719' => 'nad',
                  '720' => 'nads',
                  '721' => 'naked',
                  '722' => 'napalm',
                  '723' => 'nappy',
                  '724' => 'nazi',
                  '725' => 'nazism',
                  '726' => 'need the dick',
                  '727' => 'negro',
                  '728' => 'nigg3r',
                  '729' => 'nigg4h',
                  '730' => 'nigga',
                  '731' => 'niggah',
                  '732' => 'niggas',
                  '733' => 'niggaz',
                  '734' => 'nigger',
                  '735' => 'niggers',
                  '736' => 'niggle',
                  '737' => 'niglet',
                  '738' => 'nimrod',
                  '739' => 'ninny',
                  '740' => 'nipple',
                  '741' => 'nob',
                  '742' => 'nob jokey',
                  '743' => 'nobhead',
                  '744' => 'nobjocky',
                  '745' => 'nobjokey',
                  '746' => 'nooky',
                  '747' => 'numbnuts',
                  '748' => 'nut butter',
                  '749' => 'nutsack',
                  '750' => 'nympho',
                  '751' => 'omg',
                  '752' => 'opiate',
                  '753' => 'opium',
                  '754' => 'oral',
                  '755' => 'orally',
                  '756' => 'organ',
                  '757' => 'orgasim',
                  '758' => 'orgasims',
                  '759' => 'orgasm',
                  '760' => 'orgasmic',
                  '761' => 'orgasms',
                  '762' => 'orgies',
                  '763' => 'orgy',
                  '764' => 'ovary',
                  '765' => 'ovum',
                  '766' => 'ovums',
                  '767' => 'p.u.s.s.y.',
                  '768' => 'p0rn',
                  '769' => 'paddy',
                  '770' => 'paki',
                  '771' => 'pantie',
                  '772' => 'panties',
                  '773' => 'panty',
                  '774' => 'pastie',
                  '775' => 'pasty',
                  '776' => 'pawn',
                  '777' => 'pcp',
                  '778' => 'pecker',
                  '779' => 'pedo',
                  '780' => 'pedophile',
                  '781' => 'pedophilia',
                  '782' => 'pedophiliac',
                  '783' => 'pee',
                  '784' => 'peepee',
                  '785' => 'penetrate',
                  '786' => 'penetration',
                  '787' => 'penial',
                  '788' => 'penile',
                  '789' => 'penis',
                  '790' => 'penisfucker',
                  '791' => 'perversion',
                  '792' => 'peyote',
                  '793' => 'phalli',
                  '794' => 'phallic',
                  '795' => 'phonesex',
                  '796' => 'phuck',
                  '797' => 'phuk',
                  '798' => 'phuked',
                  '799' => 'phuking',
                  '800' => 'phukked',
                  '801' => 'phukking',
                  '802' => 'phuks',
                  '803' => 'phuq',
                  '804' => 'pigfucker',
                  '805' => 'pillowbiter',
                  '806' => 'pimp',
                  '807' => 'pimpis',
                  '808' => 'pinko',
                  '809' => 'piss',
                  '810' => 'piss-off',
                  '811' => 'pissed',
                  '812' => 'pisser',
                  '813' => 'pissers',
                  '814' => 'pisses',
                  '815' => 'pissflaps',
                  '816' => 'pissin',
                  '817' => 'pissing',
                  '818' => 'pissoff',
                  '819' => 'pissoff',
                  '820' => 'pms',
                  '821' => 'polack',
                  '822' => 'pollock',
                  '823' => 'poon',
                  '824' => 'poontang',
                  '825' => 'poop',
                  '826' => 'porn',
                  '827' => 'porno',
                  '828' => 'pornography',
                  '829' => 'pornos',
                  '830' => 'pot',
                  '831' => 'potty',
                  '832' => 'prick',
                  '833' => 'pricks',
                  '834' => 'prig',
                  '835' => 'pron',
                  '836' => 'prostitute',
                  '837' => 'prude',
                  '838' => 'pube',
                  '839' => 'pubic',
                  '840' => 'pubis',
                  '841' => 'punkass',
                  '842' => 'punky',
                  '843' => 'puss',
                  '844' => 'pusse',
                  '845' => 'pussi',
                  '846' => 'pussies',
                  '847' => 'pussy',
                  '848' => 'pussy fart',
                  '849' => 'pussy palace',
                  '850' => 'pussypounder',
                  '851' => 'pussys',
                  '852' => 'puto',
                  '853' => 'queaf',
                  '854' => 'queaf',
                  '855' => 'queef',
                  '856' => 'queer',
                  '857' => 'queero',
                  '858' => 'queers',
                  '859' => 'quicky',
                  '860' => 'quim',
                  '861' => 'r-tard',
                  '862' => 'racy',
                  '863' => 'rape',
                  '864' => 'raped',
                  '865' => 'raper',
                  '866' => 'rapist',
                  '867' => 'raunch',
                  '868' => 'rectal',
                  '869' => 'rectum',
                  '870' => 'rectus',
                  '871' => 'reefer',
                  '872' => 'reetard',
                  '873' => 'reich',
                  '874' => 'retard',
                  '875' => 'retarded',
                  '876' => 'revue',
                  '877' => 'rimjaw',
                  '878' => 'rimjob',
                  '879' => 'rimming',
                  '880' => 'ritard',
                  '881' => 'rtard',
                  '882' => 'rum',
                  '883' => 'rump',
                  '884' => 'rumprammer',
                  '885' => 'ruski',
                  '886' => 's hit',
                  '887' => 's_h_i_t',
                  '888' => 's-h-1-t',
                  '889' => 's-h-i-t',
                  '890' => 's-o-b',
                  '891' => 's.h.i.t.',
                  '892' => 's.o.b.',
                  '893' => 's0b',
                  '894' => 'sadism',
                  '895' => 'sadist',
                  '896' => 'sandbar',
                  '897' => 'sausage queen',
                  '898' => 'scag',
                  '899' => 'scantily',
                  '900' => 'schizo',
                  '901' => 'schlong',
                  '902' => 'screw',
                  '903' => 'screwed',
                  '904' => 'screwing',
                  '905' => 'scroat',
                  '906' => 'scrog',
                  '907' => 'scrot',
                  '908' => 'scrote',
                  '909' => 'scrotum',
                  '910' => 'scrud',
                  '911' => 'scum',
                  '912' => 'seaman',
                  '913' => 'seamen',
                  '914' => 'seduce',
                  '915' => 'semen',
                  '916' => 'sex',
                  '917' => 'sexual',
                  '918' => 'sh!+',
                  '919' => 'sh!t',
                  '920' => 'sh1t',
                  '921' => 'shag',
                  '922' => 'shagger',
                  '923' => 'shaggin',
                  '924' => 'shagging',
                  '925' => 'shamedame',
                  '926' => 'shemale',
                  '927' => 'shi+',
                  '928' => 'shit',
                  '929' => 'shit fucker',
                  '930' => 'shitdick',
                  '931' => 'shite',
                  '932' => 'shiteater',
                  '933' => 'shited',
                  '934' => 'shitey',
                  '935' => 'shitface',
                  '936' => 'shitfuck',
                  '937' => 'shitfull',
                  '938' => 'shithead',
                  '939' => 'shithole',
                  '940' => 'shithouse',
                  '941' => 'shiting',
                  '942' => 'shitings',
                  '943' => 'shits',
                  '944' => 'shitt',
                  '945' => 'shitted',
                  '946' => 'shitter',
                  '947' => 'shitters',
                  '948' => 'shitting',
                  '949' => 'shittings',
                  '950' => 'shitty',
                  '951' => 'shiz',
                  '952' => 'sissy',
                  '953' => 'skag',
                  '954' => 'skank',
                  '955' => 'slave',
                  '956' => 'sleaze',
                  '957' => 'sleazy',
                  '958' => 'slope',
                  '959' => 'slut',
                  '960' => 'slut bucket',
                  '961' => 'slutdumper',
                  '962' => 'slutkiss',
                  '963' => 'sluts',
                  '964' => 'smegma',
                  '965' => 'smut',
                  '966' => 'smutty',
                  '967' => 'snatch',
                  '968' => 'sniper',
                  '969' => 'snuff',
                  '970' => 'sodom',
                  '971' => 'son-of-a-bitch',
                  '972' => 'souse',
                  '973' => 'soused',
                  '974' => 'spac',
                  '975' => 'sperm',
                  '976' => 'spic',
                  '977' => 'spick',
                  '978' => 'spik',
                  '979' => 'spiks',
                  '980' => 'spooge',
                  '981' => 'spunk',
                  '982' => 'steamy',
                  '983' => 'stfu',
                  '984' => 'stiffy',
                  '985' => 'stoned',
                  '986' => 'strip',
                  '987' => 'stroke',
                  '988' => 'stupid',
                  '989' => 'suck',
                  '990' => 'sucked',
                  '991' => 'sucking',
                  '992' => 'sumofabiatch',
                  '993' => 't1t',
                  '994' => 't1tt1e5',
                  '995' => 't1tties',
                  '996' => 'tampon',
                  '997' => 'tard',
                  '998' => 'tawdry',
                  '999' => 'teabagging',
                  '1000' => 'teat',
                  '1001' => 'teets',
                  '1002' => 'teez',
                  '1003' => 'terd',
                  '1004' => 'teste',
                  '1005' => 'testee',
                  '1006' => 'testes',
                  '1007' => 'testical',
                  '1008' => 'testicle',
                  '1009' => 'testis',
                  '1010' => 'thrust',
                  '1011' => 'thug',
                  '1012' => 'tinkle',
                  '1013' => 'tit',
                  '1014' => 'tit wank',
                  '1015' => 'titfuck',
                  '1016' => 'titi',
                  '1017' => 'tits',
                  '1018' => 'titt',
                  '1019' => 'tittie5',
                  '1020' => 'tittiefucker',
                  '1021' => 'titties',
                  '1022' => 'titty',
                  '1023' => 'tittyfuck',
                  '1024' => 'tittyfucker',
                  '1025' => 'tittywank',
                  '1026' => 'titwank',
                  '1027' => 'toke',
                  '1028' => 'toots',
                  '1029' => 'tosser',
                  '1030' => 'tramp',
                  '1031' => 'transsexual',
                  '1032' => 'trashy',
                  '1033' => 'tubgirl',
                  '1034' => 'turd',
                  '1035' => 'tush',
                  '1036' => 'tw4t',
                  '1037' => 'twat',
                  '1038' => 'twathead',
                  '1039' => 'twats',
                  '1040' => 'twatty',
                  '1041' => 'twunt',
                  '1042' => 'twunter',
                  '1043' => 'ugly',
                  '1044' => 'undies',
                  '1045' => 'unwed',
                  '1046' => 'urinal',
                  '1047' => 'urine',
                  '1048' => 'uterus',
                  '1049' => 'uzi',
                  '1050' => 'v14gra',
                  '1051' => 'v1gra',
                  '1052' => 'vag',
                  '1053' => 'vagina',
                  '1054' => 'valium',
                  '1055' => 'viagra',
                  '1056' => 'virgin',
                  '1057' => 'vixen',
                  '1058' => 'vodka',
                  '1059' => 'vomit',
                  '1060' => 'voyeur',
                  '1061' => 'vulgar',
                  '1062' => 'vulva',
                  '1063' => 'w00se',
                  '1064' => 'wad',
                  '1065' => 'wang',
                  '1066' => 'wank',
                  '1067' => 'wanker',
                  '1068' => 'wanky',
                  '1069' => 'wazoo',
                  '1070' => 'wedgie',
                  '1071' => 'weed',
                  '1072' => 'weenie',
                  '1073' => 'weewee',
                  '1074' => 'weiner',
                  '1075' => 'weirdo',
                  '1076' => 'wench',
                  '1077' => 'wetback',
                  '1078' => 'wh0re',
                  '1079' => 'wh0reface',
                  '1080' => 'whitey',
                  '1081' => 'whiz',
                  '1082' => 'whoar',
                  '1083' => 'whoralicious',
                  '1084' => 'whore',
                  '1085' => 'whorealicious',
                  '1086' => 'whored',
                  '1087' => 'whoreface',
                  '1088' => 'whorehopper',
                  '1089' => 'whorehouse',
                  '1090' => 'whores',
                  '1091' => 'whoring',
                  '1092' => 'wigger',
                  '1093' => 'willies',
                  '1094' => 'willy',
                  '1095' => 'womb',
                  '1096' => 'woody',
                  '1097' => 'wop',
                  '1098' => 'wtf',
                  '1099' => 'x-rated',
                  '1100' => 'xrated',
                  '1101' => 'xxx',
                  '1102' => 'yeasty',
                  '1103' => 'yobbo',
                  '1104' => 'zoophile'
                );
      }
}  // Class DataGrab()

  } // if(!class_exists('DataGrab')

?>
